version: '3.7'

services:
  browserquest1:
    build:
      context: .
      args:
        PORT: 8001
    environment:
      - PORT=8001
    expose:
      - "8001"

  browserquest2:
    build:
      context: .
      args:
        PORT: 8002
    environment:
      - PORT=8002
    expose:
      - "8002"

  loadbalancer:
    image: nginx:latest
    volumes:
      - ./nginx1.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8000:8000"
    depends_on:
      - browserquest1
      - browserquest2

  frontend:
    build:
      context: .
      dockerfile: dockerfile.client
    ports:
      - "8080:80"

  fail2ban:
    build:
      context: ./fail2ban  # Chemin vers ton dossier fail2ban
    volumes:
      - ./logs/nginx:/var/log/nginx:ro  # Accès en lecture seule aux logs Nginx
    network_mode: "host"  # Utilisation du réseau hôte pour accéder aux logs en temps réel
    restart: unless-stopped
    depends_on:
      - loadbalancer  # fail2ban doit attendre que le loadbalancer soit en ligne
    environment:
      - LOG_PATH=/var/log/nginx/access.log  # Chemin du fichier de logs d'accès Nginx
      - MAX_RETRY=5  # Paramètre maxretry pour Fail2Ban
      - BAN_TIME=3600  # Temps de bannissement en secondes
